version: "2.0"
services:
  postgres:
    image: postgres:9.6
    volumes:
      - ${volume_base_path}/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
    restart: always
  nginx:
    image: nginx:stable
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${volume_base_path}/nginx:/etc/nginx/conf.d
    logging:
      options:
        max-size: "1Gb"
        max-file: "3"
  teamcity:
    image: ${teamcity_image}:${teamcity_tag}
    volumes:
      - ${volume_base_path}/teamcity:/data/teamcity_server/datadir
      - ${volume_base_path}/logs:/opt/teamcity/logs
    environment:
      TEAMCITY_SERVER_MEM_OPTS: "${teamcity_memory_options}"
    depends_on:
      - postgres
      - nginx
    restart: always
    logging:
      options:
        max-size: "1Gb"
        max-file: "3"
